import express from 'express';
import http from 'http';
import cors from 'cors';
import helmet from 'helmet';
import crypto from 'crypto';
import { Server } from 'socket.io';
import rateLimit from 'express-rate-limit';
import { z } from 'zod';
import { config } from './config';
import { prisma } from './prisma';
import { hashPassword, verifyPassword, signToken, requireAuth, requireRole } from './auth';
import { inKaolack, haversineKm } from './geo';
import { calculatePrice } from './pricing';
import { routeRoad } from './routing';
import { Role, DriverStatus, RideStatus, PaymentMethod, PaymentStatus, VerificationStatus, NotificationType, TicketStatus, WalletEntryType } from '@prisma/client';
import { verifyToken } from './auth';
import { notify, creditDriver, paymentProviders } from './services';

const app = express();
const server = http.createServer(app);
const io = new Server(server, { cors: { origin: config.corsOrigin === '*' ? '*' : config.corsOrigin } });
app.use(helmet()); app.use(cors({ origin: config.corsOrigin })); app.use(express.json({ limit: '1mb' }));
const authLimiter = rateLimit({windowMs: 15*60*1000, max: 60, standardHeaders: true, legacyHeaders: false});
app.use('/api/auth', authLimiter); app.use('/admin', express.static('public'));
const sha = (v:string) => crypto.createHash('sha256').update(v).digest('hex');
const otp = () => String(Math.floor(100000 + Math.random()*900000));

app.get('/health', async (_req,res)=>{ const db=await prisma.$queryRaw`SELECT 1`; res.json({ok:true,service:'yobalema-backend-v5',database:!!db,time:new Date().toISOString()}); });

const authSchema=z.object({phone:z.string().min(8),password:z.string().min(6),name:z.string().min(2).optional(),role:z.enum(['PASSENGER','DRIVER']).default('PASSENGER')});
app.post('/api/auth/register',async(req,res,next)=>{try{const b=authSchema.parse(req.body);const exists=await prisma.user.findUnique({where:{phone:b.phone}});if(exists)return res.status(409).json({error:'Numéro déjà utilisé'});const user=await prisma.user.create({data:{phone:b.phone,name:b.name,passwordHash:await hashPassword(b.password),role:b.role as Role}});if(user.role===Role.DRIVER)await prisma.driver.create({data:{userId:user.id,vehicleType:'MOTO'}});const code=otp();await prisma.otpCode.create({data:{userId:user.id,codeHash:sha(code),expiresAt:new Date(Date.now()+5*60*1000)}});res.status(201).json({token:signToken({id:user.id,role:user.role}),user:{id:user.id,phone:user.phone,name:user.name,role:user.role},devOtp:config.otpDev?code:undefined});}catch(e){next(e)}});
app.post('/api/auth/login',async(req,res,next)=>{try{const b=z.object({phone:z.string(),password:z.string()}).parse(req.body);const user=await prisma.user.findUnique({where:{phone:b.phone}});if(!user||!(await verifyPassword(b.password,user.passwordHash)))return res.status(401).json({error:'Identifiants incorrects'});res.json({token:signToken({id:user.id,role:user.role}),user:{id:user.id,phone:user.phone,name:user.name,role:user.role,phoneVerified:!!user.phoneVerifiedAt}});}catch(e){next(e)}});
app.post('/api/auth/request-otp',requireAuth,async(req,res,next)=>{try{const code=otp();await prisma.otpCode.create({data:{userId:req.user!.id,codeHash:sha(code),expiresAt:new Date(Date.now()+5*60*1000)}});res.json({sent:true,devOtp:config.otpDev?code:undefined});}catch(e){next(e)}});
app.post('/api/auth/verify-otp',requireAuth,async(req,res,next)=>{try{const b=z.object({code:z.string().length(6)}).parse(req.body);const row=await prisma.otpCode.findFirst({where:{userId:req.user!.id,consumedAt:null,expiresAt:{gt:new Date()}},orderBy:{createdAt:'desc'}});if(!row||row.codeHash!==sha(b.code))return res.status(400).json({error:'Code OTP invalide ou expiré'});await prisma.$transaction([prisma.otpCode.update({where:{id:row.id},data:{consumedAt:new Date()}}),prisma.user.update({where:{id:req.user!.id},data:{phoneVerifiedAt:new Date()}})]);res.json({verified:true});}catch(e){next(e)}});
app.get('/api/me',requireAuth,async(req,res)=>res.json(await prisma.user.findUnique({where:{id:req.user!.id},include:{driver:true}})));

const loc=z.object({lat:z.number(),lng:z.number()});
app.patch('/api/drivers/me/status',requireAuth,requireRole('DRIVER'),async(req,res,next)=>{try{const b=z.object({status:z.enum(['OFFLINE','ONLINE','BUSY'])}).parse(req.body);const driver=await prisma.driver.findUnique({where:{userId:req.user!.id}});if(!driver)return res.status(404).json({error:'Profil chauffeur absent'});if(b.status==='ONLINE'&&(driver.verificationStatus!==VerificationStatus.VERIFIED||driver.vehicleType!=='MOTO'||!driver.vehiclePlate))return res.status(403).json({error:'Chauffeur non vérifié ou moto incomplète'});res.json(await prisma.driver.update({where:{userId:req.user!.id},data:{status:b.status as DriverStatus,vehicleType:'MOTO'}}));}catch(e){next(e)}});
app.patch('/api/drivers/me/location',requireAuth,requireRole('DRIVER'),async(req,res,next)=>{try{const b=loc.parse(req.body);if(!inKaolack(b.lat,b.lng))return res.status(400).json({error:'Position hors périmètre Yobalema'});const d=await prisma.driver.update({where:{userId:req.user!.id},data:b});io.to(`ride-driver:${req.user!.id}`).emit('driver:location',{driverId:d.id,lat:b.lat,lng:b.lng});res.json(d);}catch(e){next(e)}});
app.patch('/api/drivers/me/vehicle',requireAuth,requireRole('DRIVER'),async(req,res,next)=>{try{const b=z.object({vehicleType:z.literal('MOTO'),vehiclePlate:z.string().trim().min(2).max(30)}).parse(req.body);res.json(await prisma.driver.update({where:{userId:req.user!.id},data:{vehicleType:'MOTO',vehiclePlate:b.vehiclePlate}}));}catch(e){next(e)}});

const quoteSchema=z.object({fromName:z.string().trim().min(2),toName:z.string().trim().min(2),fromLat:z.number(),fromLng:z.number(),toLat:z.number(),toLng:z.number(),fromZone:z.enum(['CITY','PERIURBAN','VILLAGE']),toZone:z.enum(['CITY','PERIURBAN','VILLAGE']),trafficLevel:z.number().int().min(0).max(3).default(0),night:z.boolean().default(false)});
async function makeQuote(b:z.infer<typeof quoteSchema>){
  if(!inKaolack(b.fromLat,b.fromLng)||!inKaolack(b.toLat,b.toLng))throw new Error('Départ et destination doivent être dans la région de Kaolack');
  if(Math.abs(b.fromLat-b.toLat)<1e-10&&Math.abs(b.fromLng-b.toLng)<1e-10)return {km:0,durationMin:0,geometry:[{lat:b.fromLat,lng:b.fromLng}],price:calculatePrice(0,b.fromZone,b.toZone,b.trafficLevel,b.night)};
  const route=await routeRoad(b.fromLat,b.fromLng,b.toLat,b.toLng);
  if(!route)throw new Error('Itinéraire routier indisponible. Aucun devis approximatif ne sera présenté.');
  return {km:route.distanceKm,durationMin:route.durationMin,geometry:route.geometry,price:calculatePrice(route.distanceKm,b.fromZone,b.toZone,b.trafficLevel,b.night)};
}
app.post('/api/rides/quote',requireAuth,async(req,res,next)=>{try{const b=quoteSchema.parse(req.body);const q=await makeQuote(b);res.json({distanceKm:Number(q.km.toFixed(3)),durationMin:Number(q.durationMin.toFixed(1)),routeGeometry:q.geometry,...q.price});}catch(e){next(e)}});
const rideSchema=quoteSchema.extend({shareTrip:z.boolean().default(false),paymentMethod:z.enum(['CASH','WAVE','ORANGE_MONEY']).default('CASH')});
app.post('/api/rides',requireAuth,requireRole('PASSENGER'),async(req,res,next)=>{try{const b=rideSchema.parse(req.body);const q=await makeQuote(b);const ride=await prisma.ride.create({data:{passengerId:req.user!.id,fromName:b.fromName,toName:b.toName,fromLat:b.fromLat,fromLng:b.fromLng,toLat:b.toLat,toLng:b.toLng,distanceKm:q.km,zone:q.price.zone,trafficLevel:b.trafficLevel,night:b.night,priceFcfa:q.price.total,driverEarnings:q.price.driver,platformFee:q.price.platform,shareTrip:b.shareTrip,paymentMethod:b.paymentMethod as PaymentMethod,paymentStatus:PaymentStatus.PENDING,payment:{create:{method:b.paymentMethod as PaymentMethod,amountFcfa:q.price.total}}},include:{payment:true}});const candidates=await prisma.driver.findMany({where:{status:DriverStatus.ONLINE,verificationStatus:VerificationStatus.VERIFIED,vehicleType:'MOTO',lat:{not:null},lng:{not:null}}});const ranked=candidates.map(d=>({...d,distanceKm:haversineKm(b.fromLat,b.fromLng,d.lat!,d.lng!)})).filter(d=>d.distanceKm<=10).sort((a,b)=>a.distanceKm-b.distanceKm).slice(0,3);if(ranked.length){io.to(`driver:${ranked[0].userId}`).emit('ride:offer',{rideId:ride.id,from:b.fromName,to:b.toName,lat:b.fromLat,lng:b.fromLng,priceFcfa:ride.priceFcfa,distanceKm:Number(ranked[0].distanceKm.toFixed(2))});await notify(ranked[0].userId,NotificationType.RIDE,'Nouvelle course',`Course ${b.fromName} → ${b.toName}`,{rideId:ride.id});}else{io.to(`passenger:${req.user!.id}`).emit('ride:waiting',{rideId:ride.id});await notify(req.user!.id,NotificationType.RIDE,'Recherche en cours','Nous cherchons un chauffeur disponible.',{rideId:ride.id});}res.status(201).json({ride,quote:{...q.price,distanceKm:Number(q.km.toFixed(3)),durationMin:Number(q.durationMin.toFixed(1)),routeGeometry:q.geometry},matching:{status:ranked.length?'DRIVER_NOTIFIED':'SEARCHING',candidates:ranked.length}});}catch(e){next(e)}});
app.get('/api/rides',requireAuth,async(req,res,next)=>{try{res.json(await prisma.ride.findMany({where:req.user!.role==='DRIVER'?{driverId:req.user!.id}:{passengerId:req.user!.id},orderBy:{createdAt:'desc'},take:50,include:{payment:true,ratings:true}}));}catch(e){next(e)}});
app.get('/api/rides/:id',requireAuth,async(req,res,next)=>{try{const id=Array.isArray(req.params.id)?req.params.id[0]:req.params.id;const ride=await prisma.ride.findUnique({where:{id:id as string},include:{payment:true,ratings:true,passenger:{select:{id:true,name:true,phone:true}},driver:{select:{id:true,name:true,phone:true,driver:true}}}});if(!ride)return res.status(404).json({error:'Course introuvable'});if(ride.passengerId!==req.user!.id&&ride.driverId!==req.user!.id&&req.user!.role!=='ADMIN')return res.status(403).json({error:'Accès interdit'});res.json(ride);}catch(e){next(e)}});
app.post('/api/rides/:id/accept',requireAuth,requireRole('DRIVER'),async(req,res,next)=>{try{const id=Array.isArray(req.params.id)?req.params.id[0]:req.params.id;const d=await prisma.driver.findUnique({where:{userId:req.user!.id}});if(!d||d.status!==DriverStatus.ONLINE||d.verificationStatus!==VerificationStatus.VERIFIED||d.vehicleType!=='MOTO')return res.status(409).json({error:'Chauffeur moto non disponible'});const updated=await prisma.$transaction(async tx=>{const latest=await tx.ride.findUnique({where:{id:id as string}});if(!latest||latest.status!==RideStatus.REQUESTED)throw new Error('Course déjà prise ou non disponible');const u=await tx.ride.update({where:{id:latest.id},data:{driverId:req.user!.id,status:RideStatus.ACCEPTED}});await tx.driver.update({where:{id:d.id},data:{status:DriverStatus.BUSY,vehicleType:'MOTO'}});return u;});io.to(`ride:${id}`).emit('ride:accepted',{rideId:id,driverId:req.user!.id});io.to(`passenger:${updated.passengerId}`).emit('ride:accepted',{rideId:id,driverId:req.user!.id});await notify(updated.passengerId,NotificationType.RIDE,'Chauffeur trouvé','Votre chauffeur a accepté la course.',{rideId:id,driverId:req.user!.id});res.json(updated);}catch(e){next(e)}});

app.post('/api/rides/:id/pickup-otp',requireAuth,async(req,res,next)=>{try{const id=Array.isArray(req.params.id)?req.params.id[0]:req.params.id;const ride=await prisma.ride.findUnique({where:{id:id as string}});if(!ride||ride.passengerId!==req.user!.id)return res.status(403).json({error:'Accès interdit'});if(ride.status!==RideStatus.ACCEPTED&&ride.status!==RideStatus.DRIVER_ARRIVING)return res.status(409).json({error:'Course non prête'});const code=otp();await prisma.ride.update({where:{id:ride.id},data:{otpPickupHash:sha(code)}});res.json({sent:true,devOtp:config.otpDev?code:undefined});}catch(e){next(e)}});
app.post('/api/rides/:id/verify-pickup',requireAuth,requireRole('DRIVER'),async(req,res,next)=>{try{const b=z.object({code:z.string().length(6)}).parse(req.body);const id=Array.isArray(req.params.id)?req.params.id[0]:req.params.id;const ride=await prisma.ride.findUnique({where:{id:id as string}});if(!ride||ride.driverId!==req.user!.id||!ride.otpPickupHash||ride.otpPickupHash!==sha(b.code))return res.status(400).json({error:'OTP de départ invalide'});const u=await prisma.ride.update({where:{id:ride.id},data:{pickupVerifiedAt:new Date(),status:RideStatus.IN_PROGRESS}});io.to(`ride:${ride.id}`).emit('ride:status',{rideId:ride.id,status:u.status});res.json(u);}catch(e){next(e)}});

app.patch('/api/rides/:id/status',requireAuth,async(req,res,next)=>{try{const b=z.object({status:z.enum(['DRIVER_ARRIVING','IN_PROGRESS','COMPLETED','CANCELLED'])}).parse(req.body);const id=Array.isArray(req.params.id)?req.params.id[0]:req.params.id;const ride=await prisma.ride.findUnique({where:{id:id as string}});if(!ride)return res.status(404).json({error:'Course introuvable'});if(ride.passengerId!==req.user!.id&&ride.driverId!==req.user!.id)return res.status(403).json({error:'Accès interdit'});if(b.status==='IN_PROGRESS'&&!ride.pickupVerifiedAt)return res.status(409).json({error:'OTP de départ requis'});const u=await prisma.ride.update({where:{id:ride.id},data:{status:b.status as RideStatus}});if(b.status==='COMPLETED'){const paidNow=ride.paymentMethod===PaymentMethod.CASH;await prisma.ride.update({where:{id:ride.id},data:{paymentStatus:paidNow?PaymentStatus.PAID:PaymentStatus.PENDING}});if(ride.driverId){await prisma.driver.update({where:{userId:ride.driverId},data:{status:DriverStatus.ONLINE,totalTrips:{increment:1},vehicleType:'MOTO'}});if(paidNow){await creditDriver(ride.driverId,ride.driverEarnings,ride.id,'Commission chauffeur course terminée');await notify(ride.driverId,NotificationType.PAYMENT,'Course terminée',`+${ride.driverEarnings} FCFA crédités`,{rideId:ride.id});}else{await notify(ride.driverId,NotificationType.PAYMENT,'Paiement en attente','Le paiement électronique doit être confirmé.',{rideId:ride.id});}await notify(ride.passengerId,NotificationType.RIDE,'Course terminée','Merci d’avoir utilisé Yobalema.',{rideId:ride.id});}}if(b.status==='CANCELLED'&&ride.driverId)await prisma.driver.update({where:{userId:ride.driverId},data:{status:DriverStatus.ONLINE,vehicleType:'MOTO'}});io.to(`ride:${ride.id}`).emit('ride:status',{rideId:ride.id,status:b.status});res.json(u);}catch(e){next(e)}});

app.post('/api/rides/:id/payment/confirm',requireAuth,async(req,res,next)=>{try{const id=Array.isArray(req.params.id)?req.params.id[0]:req.params.id;const b=z.object({providerRef:z.string().min(3)}).parse(req.body);const ride=await prisma.ride.findUnique({where:{id:id as string},include:{payment:true}});if(!ride||ride.passengerId!==req.user!.id)return res.status(403).json({error:'Accès interdit'});if(ride.paymentMethod===PaymentMethod.CASH)return res.status(400).json({error:'Paiement espèces'});if(ride.status!==RideStatus.COMPLETED)return res.status(409).json({error:'Course non terminée'});const now=new Date();const p=await prisma.payment.update({where:{rideId:ride.id},data:{status:PaymentStatus.PAID,providerRef:b.providerRef,paidAt:now}});await prisma.ride.update({where:{id:ride.id},data:{paymentStatus:PaymentStatus.PAID}});res.json(p);}catch(e){next(e)}});

app.post('/api/payments/webhook/:provider',async(req,res,next)=>{try{const signature=String(req.headers['x-yobalema-signature']||'');const raw=JSON.stringify(req.body);const expected=crypto.createHmac('sha256',config.paymentWebhookSecret).update(raw).digest('hex');if(signature.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(signature),Buffer.from(expected)))return res.status(401).json({error:'Signature webhook invalide'});const b=z.object({rideId:z.string(),providerRef:z.string().min(3),status:z.enum(['PAID','FAILED','REFUNDED'])}).parse(req.body);const ride=await prisma.ride.findUnique({where:{id:b.rideId},include:{payment:true}});if(!ride||!ride.payment)return res.status(404).json({error:'Paiement introuvable'});const status=b.status as PaymentStatus;await prisma.$transaction(async tx=>{await tx.payment.update({where:{rideId:ride.id},data:{status,providerRef:b.providerRef,paidAt:status===PaymentStatus.PAID?new Date():undefined}});await tx.ride.update({where:{id:ride.id},data:{paymentStatus:status}});});if(status===PaymentStatus.PAID&&ride.driverId){await creditDriver(ride.driverId,ride.driverEarnings,`PAY-${ride.id}`,'Paiement électronique confirmé');await notify(ride.driverId,NotificationType.PAYMENT,'Paiement reçu',`+${ride.driverEarnings} FCFA crédités`,{rideId:ride.id});}res.json({ok:true,rideId:ride.id,status});}catch(e){next(e)}});

app.post('/api/rides/:id/rating',requireAuth,async(req,res,next)=>{try{const b=z.object({score:z.number().int().min(1).max(5),comment:z.string().max(500).optional()}).parse(req.body);const id=Array.isArray(req.params.id)?req.params.id[0]:req.params.id;const ride=await prisma.ride.findUnique({where:{id:id as string}});if(!ride||ride.status!==RideStatus.COMPLETED||!ride.driverId)return res.status(409).json({error:'Course non éligible'});if(req.user!.id!==ride.passengerId&&req.user!.id!==ride.driverId)return res.status(403).json({error:'Accès interdit'});const to=req.user!.id===ride.passengerId?ride.driverId:ride.passengerId;const r=await prisma.rating.create({data:{rideId:ride.id,fromUserId:req.user!.id,toUserId:to,score:b.score,comment:b.comment}});if(to===ride.driverId){const all=await prisma.rating.aggregate({where:{toUserId:to},_avg:{score:true}});await prisma.driver.update({where:{userId:to},data:{rating:all._avg.score??5}});}res.status(201).json(r);}catch(e){next(e)}});

app.get('/api/drivers/nearby',requireAuth,async(req,res,next)=>{try{const q=req.query;const latRaw=Array.isArray(q.lat)?q.lat[0]:q.lat;const lngRaw=Array.isArray(q.lng)?q.lng[0]:q.lng;const radiusRaw=Array.isArray(q.radiusKm)?q.radiusKm[0]:q.radiusKm;const b=loc.extend({radiusKm:z.number().min(.1).max(50).default(5)}).parse({lat:Number(latRaw),lng:Number(lngRaw),radiusKm:Number(radiusRaw??5)});if(!inKaolack(b.lat,b.lng))return res.status(400).json({error:'Position hors périmètre Yobalema'});const ds=await prisma.driver.findMany({where:{status:DriverStatus.ONLINE,verificationStatus:VerificationStatus.VERIFIED,vehicleType:'MOTO',lat:{not:null},lng:{not:null}}});res.json(ds.map(d=>({...d,distanceKm:haversineKm(b.lat,b.lng,d.lat!,d.lng!)})).filter(d=>d.distanceKm<=b.radiusKm).sort((a,b)=>a.distanceKm-b.distanceKm).slice(0,10));}catch(e){next(e)}});

app.get('/api/notifications',requireAuth,async(req,res,next)=>{try{res.json(await prisma.notification.findMany({where:{userId:req.user!.id},orderBy:{createdAt:'desc'},take:50}));}catch(e){next(e)}});
app.patch('/api/notifications/:id/read',requireAuth,async(req,res,next)=>{try{const id=Array.isArray(req.params.id)?req.params.id[0]:req.params.id;const n=await prisma.notification.updateMany({where:{id:id as string,userId:req.user!.id},data:{readAt:new Date()}});res.json({ok:n.count===1});}catch(e){next(e)}});
app.post('/api/support/tickets',requireAuth,async(req,res,next)=>{try{const b=z.object({subject:z.string().min(3).max(120),message:z.string().min(5).max(2000)}).parse(req.body);const t=await prisma.supportTicket.create({data:{userId:req.user!.id,subject:b.subject,message:b.message}});res.status(201).json(t);}catch(e){next(e)}});
app.get('/api/support/tickets',requireAuth,async(req,res,next)=>{try{res.json(await prisma.supportTicket.findMany({where:{userId:req.user!.id},orderBy:{createdAt:'desc'}}));}catch(e){next(e)}});
app.get('/api/drivers/me/wallet',requireAuth,requireRole('DRIVER'),async(req,res,next)=>{try{const entries=await prisma.walletEntry.findMany({where:{userId:req.user!.id},orderBy:{createdAt:'desc'},take:100});const balance=entries.reduce((sum,e)=>sum+(e.type===WalletEntryType.CREDIT?e.amountFcfa:-e.amountFcfa),0);res.json({balanceFcfa:balance,entries});}catch(e){next(e)}});
app.post('/api/rides/:id/payment/start',requireAuth,async(req,res,next)=>{try{const id=Array.isArray(req.params.id)?req.params.id[0]:req.params.id;const ride=await prisma.ride.findUnique({where:{id:id as string},include:{payment:true}});if(!ride||ride.passengerId!==req.user!.id)return res.status(403).json({error:'Accès interdit'});if(ride.paymentMethod===PaymentMethod.CASH)return res.status(400).json({error:'Paiement espèces'});if(ride.status!==RideStatus.COMPLETED)return res.status(409).json({error:'Course non terminée'});const reference=`YBL-${ride.id}-${Date.now()}`;const result=ride.paymentMethod===PaymentMethod.WAVE?await paymentProviders.wave.createPayment(ride.priceFcfa,reference):await paymentProviders.orangeMoney.createPayment(ride.priceFcfa,reference);res.json(result);}catch(e){next(e)}});
app.get('/api/admin/support/tickets',requireAuth,requireRole('ADMIN'),async(_req,res,next)=>{try{res.json(await prisma.supportTicket.findMany({include:{user:{select:{id:true,name:true,phone:true}}},orderBy:{createdAt:'desc'},take:100}));}catch(e){next(e)}});
app.patch('/api/admin/support/tickets/:id',requireAuth,requireRole('ADMIN'),async(req,res,next)=>{try{const id=Array.isArray(req.params.id)?req.params.id[0]:req.params.id;const b=z.object({status:z.enum(['OPEN','IN_PROGRESS','RESOLVED','CLOSED']),adminNote:z.string().max(1000).optional()}).parse(req.body);const t=await prisma.supportTicket.update({where:{id:id as string},data:{status:b.status as TicketStatus,adminNote:b.adminNote}});await notify(t.userId,NotificationType.SUPPORT,'Mise à jour du support',`Votre demande est maintenant ${b.status}.`);res.json(t);}catch(e){next(e)}});
app.get('/api/admin/wallet',requireAuth,requireRole('ADMIN'),async(_req,res,next)=>{try{res.json(await prisma.walletEntry.findMany({orderBy:{createdAt:'desc'},take:200}));}catch(e){next(e)}});
app.get('/api/admin/stats',requireAuth,requireRole('ADMIN'),async(_req,res,next)=>{try{const [users,drivers,rides,completed,revenue,paid]=await Promise.all([prisma.user.count(),prisma.driver.count(),prisma.ride.count(),prisma.ride.count({where:{status:RideStatus.COMPLETED}}),prisma.ride.aggregate({where:{status:RideStatus.COMPLETED},_sum:{platformFee:true}}),prisma.payment.aggregate({where:{status:PaymentStatus.PAID},_sum:{amountFcfa:true}})]);res.json({users,drivers,rides,completedRides:completed,platformRevenueFcfa:revenue._sum.platformFee??0,paidVolumeFcfa:paid._sum.amountFcfa??0});}catch(e){next(e)}});
app.get('/api/admin/drivers',requireAuth,requireRole('ADMIN'),async(_req,res,next)=>{try{res.json(await prisma.driver.findMany({include:{user:{select:{id:true,name:true,phone:true}}},orderBy:{updatedAt:'desc'}}));}catch(e){next(e)}});
app.patch('/api/admin/drivers/:userId/verification',requireAuth,requireRole('ADMIN'),async(req,res,next)=>{try{const userId=Array.isArray(req.params.userId)?req.params.userId[0]:req.params.userId;const b=z.object({status:z.enum(['PENDING','VERIFIED','REJECTED']),note:z.string().max(500).optional()}).parse(req.body);res.json(await prisma.driver.update({where:{userId:userId as string},data:{verificationStatus:b.status as VerificationStatus,verificationNote:b.note,vehicleType:'MOTO'}}));}catch(e){next(e)}});

io.use((socket,next)=>{try{const raw=String(socket.handshake.auth?.token||'');const token=raw.replace(/^Bearer\s+/i,'').trim();if(!token)return next(new Error('UNAUTHORIZED'));socket.data.auth=verifyToken(token);socket.data.userId=socket.data.auth.id;next();}catch(_e){next(new Error('UNAUTHORIZED'));}});
io.on('connection',(socket)=>{const userId=socket.data.userId as string;socket.join(`user:${userId}`);socket.on('driver:join',()=>socket.join(`driver:${userId}`));socket.on('passenger:join',()=>socket.join(`passenger:${userId}`));socket.on('ride:join',async(rideId:string)=>{const ride=await prisma.ride.findUnique({where:{id:rideId}});if(ride&&(ride.passengerId===userId||ride.driverId===userId||socket.data.auth.role==='ADMIN'))socket.join(`ride:${rideId}`);});socket.on('ride:location',async(data:{rideId:string,lat:number,lng:number})=>{if(!inKaolack(data.lat,data.lng))return;const ride=await prisma.ride.findUnique({where:{id:data.rideId}});if(ride?.driverId===userId)io.to(`ride:${data.rideId}`).emit('ride:location',data);});});
app.use((err:any,_req:any,res:any,_next:any)=>{console.error(err);res.status(400).json({error:err?.issues?.[0]?.message??err?.message??'Erreur serveur'});});
server.listen(config.port,()=>console.log(`Yobalema V5 backend écoute sur http://localhost:${config.port}`));
process.on('SIGINT',async()=>{await prisma.$disconnect();process.exit(0)});
